### PR TITLE
Bump scie-pants v0.2.2

### PR DESCRIPTION
**Pull request by kaos**

### CODE REVIEW

**Comment by kaos** [comment]
Used the new update script @benjyw set the foundation for, worked really well. 🎉 
image

**Review by sureshjoshi — APPROVED** [review]

**Comment by sureshjoshi** [comment]
@kaos Is that script in a repo or gist somewhere?

**Comment by kaos** [comment]
yep, in the root of this repo :)

**Comment by sureshjoshi** [comment]
Whoa, that's so weird - I was looking for it, but couldn't see it on my phone's github app.

**Comment by kaos** [comment]
Weird indeed.

**Pull request merged**
